/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWatchesRouteImport } from './routes/api/watches'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiPollRouteImport } from './routes/api/poll'
import { Route as ApiMatchesRouteImport } from './routes/api/matches'
import { Route as ApiWatchesIdRouteImport } from './routes/api/watches.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchesRoute = ApiWatchesRouteImport.update({
  id: '/api/watches',
  path: '/api/watches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPollRoute = ApiPollRouteImport.update({
  id: '/api/poll',
  path: '/api/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesRoute = ApiMatchesRouteImport.update({
  id: '/api/matches',
  path: '/api/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchesIdRoute = ApiWatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWatchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/matches': typeof ApiMatchesRoute
  '/api/poll': typeof ApiPollRoute
  '/api/search': typeof ApiSearchRoute
  '/api/watches': typeof ApiWatchesRouteWithChildren
  '/api/watches/$id': typeof ApiWatchesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/matches': typeof ApiMatchesRoute
  '/api/poll': typeof ApiPollRoute
  '/api/search': typeof ApiSearchRoute
  '/api/watches': typeof ApiWatchesRouteWithChildren
  '/api/watches/$id': typeof ApiWatchesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/matches': typeof ApiMatchesRoute
  '/api/poll': typeof ApiPollRoute
  '/api/search': typeof ApiSearchRoute
  '/api/watches': typeof ApiWatchesRouteWithChildren
  '/api/watches/$id': typeof ApiWatchesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/matches'
    | '/api/poll'
    | '/api/search'
    | '/api/watches'
    | '/api/watches/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/matches'
    | '/api/poll'
    | '/api/search'
    | '/api/watches'
    | '/api/watches/$id'
  id:
    | '__root__'
    | '/'
    | '/api/matches'
    | '/api/poll'
    | '/api/search'
    | '/api/watches'
    | '/api/watches/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMatchesRoute: typeof ApiMatchesRoute
  ApiPollRoute: typeof ApiPollRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiWatchesRoute: typeof ApiWatchesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watches': {
      id: '/api/watches'
      path: '/api/watches'
      fullPath: '/api/watches'
      preLoaderRoute: typeof ApiWatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/poll': {
      id: '/api/poll'
      path: '/api/poll'
      fullPath: '/api/poll'
      preLoaderRoute: typeof ApiPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches': {
      id: '/api/matches'
      path: '/api/matches'
      fullPath: '/api/matches'
      preLoaderRoute: typeof ApiMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watches/$id': {
      id: '/api/watches/$id'
      path: '/$id'
      fullPath: '/api/watches/$id'
      preLoaderRoute: typeof ApiWatchesIdRouteImport
      parentRoute: typeof ApiWatchesRoute
    }
  }
}

interface ApiWatchesRouteChildren {
  ApiWatchesIdRoute: typeof ApiWatchesIdRoute
}

const ApiWatchesRouteChildren: ApiWatchesRouteChildren = {
  ApiWatchesIdRoute: ApiWatchesIdRoute,
}

const ApiWatchesRouteWithChildren = ApiWatchesRoute._addFileChildren(
  ApiWatchesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMatchesRoute: ApiMatchesRoute,
  ApiPollRoute: ApiPollRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiWatchesRoute: ApiWatchesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
